// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FresnoDailyNews.proto

package org.fresno.adapter.grpc;

public interface ExtractKeywordsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fresnodailynews.ExtractKeywordsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   * @return The reply.
   */
  String getReply();
  /**
   * <code>string reply = 1;</code>
   * @return The bytes for reply.
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
