// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FresnoDailyNews.proto

package org.fresno.adapter.grpc;

public interface ExtractKeywordsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fresnodailynews.ExtractKeywordsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
