// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FresnoDailyNews.proto

package org.fresno.adapter.grpc;

public final class FresnoDailyNewsService {
  private FresnoDailyNewsService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fresnodailynews_ExtractKeywordsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fresnodailynews_ExtractKeywordsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fresnodailynews_ExtractKeywordsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fresnodailynews_ExtractKeywordsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025FresnoDailyNews.proto\022\017fresnodailynews" +
      "\")\n\026ExtractKeywordsRequest\022\017\n\007message\030\001 " +
      "\001(\t\"(\n\027ExtractKeywordsResponse\022\r\n\005reply\030" +
      "\001 \001(\t2x\n\017FresnoDailyNews\022e\n\016ExtractKeywo" +
      "rd\022\'.fresnodailynews.ExtractKeywordsRequ" +
      "est\032(.fresnodailynews.ExtractKeywordsRes" +
      "ponse\"\000B3\n\027org.fresno.adapter.grpcB\026Fres" +
      "noDailyNewsServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fresnodailynews_ExtractKeywordsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fresnodailynews_ExtractKeywordsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fresnodailynews_ExtractKeywordsRequest_descriptor,
        new String[] { "Message", });
    internal_static_fresnodailynews_ExtractKeywordsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fresnodailynews_ExtractKeywordsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fresnodailynews_ExtractKeywordsResponse_descriptor,
        new String[] { "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
